server:
  port: 8090

#微信配置
wechat:
  #微信支付配置
  pay:
    appId: xxxxx
    mchId: xxxxx
    mchKey: xxxxx
    keyPath: xxxxx
    payNotify: xxxxx
    refundNotify: xxxxx
  #微信公众号配置
  mp:
    appId: xxxxx
    secret: xxxxx
    token: xxxxx
    aesKey: xxxxx
  #微信小程序配置
  ma:
    appId: xxxxx
    secret: xxxxx
    token: xxxxx
    aesKey: xxxxx
    msgDataFormat: JSON

