server:
  port: 8090

wx:
  pay:
    # 微信支付
    appId: xxx
    mchId: xxx
    mchKey: xxx
    keyPath: classpath:xxx
    payNotify: xxx
    refundNotify: xxx
    # 微信支付分（serviceId设置成字符串）
    serviceId: "00002004000000640364551442486693"
    privateKeyPath: classpath:xxx
    privateCertPath: classpath:xxx
    certSerialNo: xxx
    apiv3Key: xxx
    payScoreNotifyUrl: xxx
  mp:
    appId: xxxxx
    secret: xxxxx
    token: xxxxx
    aesKey: xxxxx
  ma:
    appId: xxxxx
    secret: xxxxx
    token: xxxxx
    aesKey: xxxxx
    msgDataFormat: JSON

spring:
  redis:
    host: 123.57.243.185
    port: 6379
    timeout: 2000
    database: 1