server:
  port: 8090

wx:
  pay:
    appId: xxxxx
    mchId: xxxxx
    mchKey: xxxxx
    #subAppId: xxxxx
    #subMchId: xxxxx
    keyPath: classpath:apiclient_cert.p12
    payNotify: xxxxx
    refundNotify: xxxxx
  mp:
    appId: xxxxx
    secret: xxxxx
    token: xxxxx
    aesKey: xxxxx
  ma:
    appId: xxxxx
    secret: xxxxx
    token: xxxxx
    aesKey: xxxxx
    msgDataFormat: JSON

