server:
  port: 8090

#微信配置
wechat:
  #微信支付配置
  pay:
    appId: wxbaa75fbc1e41f2f1
    mchId: 1490644372
    mchKey: nYiZ9SeHyW0zuxQi68DaiwaVQBmWuqwe
    keyPath: classpath:app_apiclient_cert.p12
    payNotify: http://woodyc.ngrok2.xiaomiqiu.cn/payNotify
    refundNotify: http://woodyc.ngrok2.xiaomiqiu.cn/refundNotify
  #微信公众号配置
  mp:
    appId: wx0a7e5948e3247bae
    secret: 85a48d33bd268c7f3cf3fc0cd2395efd
    token: woodyclub
    aesKey: ipuPBNs3wgXoSOVjoHGVFeucArPDu35f0glDTozUoMB
  #微信小程序配置
  ma:
    appId: wxbaa75fbc1e41f2f1
    secret: 9c367fc02615461d49ec2d94e444e16a
    token: woodylibrary1215
    aesKey: KpLzada3vmCrLK9V4bEiX3TSmxJ2Dr5pwRNXXmL6G9q
    msgDataFormat: JSON

